name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 New Features'
    labels:
      - feature
  - title: '🐛 Bug Fixes'
    labels:
      - bug
  - title: '🔧 Improvements'
    labels:
      - enhancement
      - optimization
      - refactor
  - title: '🛠 Maintenance'
    labels:
      - chore
template: |
  ## What's Changed

  $CHANGES

  ---