# Base image for AWS Lambda
FROM public.ecr.aws/lambda/python:3.9

# Set working directory
WORKDIR /var/task

# Copy source code and dependencies
COPY .morph/app.py /var/task/app.py
COPY .morph/frontend/dist /var/task/.morph/frontend/dist

# Install Python dependencies with poetry
COPY poetry.lock pyproject.toml /var/task/
RUN pip install --no-cache-dir poetry && poetry install --no-dev --no-interaction

# Command to run the Lambda function
CMD ["main.handler"]
