# Base image for AWS Lambda
FROM public.ecr.aws/lambda/python:3.9

# Set working directory
WORKDIR /var/task

# Copy source code and dependencies
COPY .morph/main.py /var/task/main.py
COPY .morph/frontend/dist /var/task/dist
COPY .morph/frontend/src /var/task/src

# Install Python dependencies with pip
COPY requirements.txt /var/task/
RUN pip install --no-cache-dir -r requirements.txt

# Command to run the Lambda function
CMD ["main.handler"]
