import {
  Accordion,
  Alert,
  Card,
  DataTable,
  Embed,
  Grid,
  Img,
  LLM,
  Metrics,
  MetricsGrid,
  Panel,
  Stack,
  Tab,
  Tabs,
  VarDatePicker,
  VariableDatePicker,
  VariableInput,
  VariableSelect,
  VariableValue,
  VarInput,
  VarValue,
} from "@use-morph/page";
import { MDXComponents } from "mdx/types";

export const customMDXComponents: MDXComponents = {
  DataTable,
  Embed,
  Metrics,
  MetricsGrid,
  VariableInput,
  VarInput,
  VariableValue,
  VarValue,
  VariableDatePicker,
  VarDatePicker,
  VariableSelect: VariableSelect.Root,
  VarSelect: VariableSelect.Root,
  VariableSelectGroup: VariableSelect.Group,
  VarSelectGroup: VariableSelect.Group,
  VariableSelectLabel: VariableSelect.Label,
  VarSelectLabel: VariableSelect.Label,
  VariableSelectItem: VariableSelect.Item,
  VarSelectItem: VariableSelect.Item,
  VariableSelectItems: VariableSelect.Items,
  VarSelectItems: VariableSelect.Items,
  VariableSelectSeparator: VariableSelect.Separator,
  VarSelectSeparator: VariableSelect.Separator,
  Value: VariableValue,
  Stack: Stack,
  Card: Card.Root,
  Grid,
  Panel,
  Tabs,
  Tab,
  Accordion,
  Alert,
  Img,
  LLM,
};
